VARIABLE_DESCRIPTION = {
    "time": "Time, s",
    "ub": "Body-axis x inertial velocity, ub, m/s",
    "vb": "Body-axis y inertial velocity, vb, m/s",
    "wb": "Body-axis z inertial velocity, wb, m/s",
    "xe": "North position of center of mass WRT Earth, xe, m",
    "ye": "East position of center of mass WRT Earth, ye, m",
    "ze": "Negative altitude WRT Earth, ze=-h, m",
    "pr": "Body axis roll rate, pr, rad/s",
    "qr": "Body axis pitch rate, qr, rad/s",
    "rr": "Body axis yaw rate, rr, rad/s",
    "phir": "Roll angle of body WRT Earth, phir, rad",
    "thetar": "Pitch angle of body WRT Earth, thetar, rad",
    "psir": "Yaw angle of body WRT Earth, psir, rad",
    "m": "Mass of the aircraft, m, kg",
    "fl": "Position of the flaps, fl, rad",
    "ice": "Proportion of icing on the aircraft, ice, %",
    "ge": "Position of the landing gear, ge, rad",
    "dEr": "Elevator, dEr, rad, positive: trailing edge down",
    "dAr": "Aileron, dAr, rad, positive: left trailing edge down",
    "dRr": "Rudder, dRr, rad, positive: trailing edge left",
    "dT": "Throttle, dT, %",
    "dASr": "Asymmetric Spoiler, dASr, rad",
    "dFr": "Flap command, dFr, rad",
    "dSr": "Stabilator, dSr, rad",
    "dGe": "Gear command, dGe, boolean",
    "tgammar": "Target flight path angle gamma, tgammar, rad",
    "tphir": "Target roll angle phi, tphir, rad",
    "txir": "Target route Xi, txir, rad",
    "ttas": "Target air speed, ttas, m/s",
    "th": "Target altitude, th, m",
    "tfl": "Flap instruction, tfl, rad",
    "cx": "Drag coefficient, cx",
    "cz": "Lift coefficient, cz",
    "cy": "Lateral force coefficient, cy",
    "cl": "x-axis moment, cl",
    "cm": "y-axis moment, cm",
    "cn": "z-axis moment, cn",
    "thr": "Thrust, thr, N",
    "rho": "Air density, rho, kg/m^3",
    "p": "Air pressure, p, Pa",
    "temp": "Air temperature, temp, K",
    "tas": "True air speed, tas, m/s",
    "mach": "Mach number, mach",
    "alphar": "Angle of attack, alphar, rad",
    "betar": "Sideslip angle, betar, rad",
    "gammar": "Flight path angle, gammar, rad",
    "xir": "Route angle, xir, rad",
    "nx": "X load factor, nx",
    "ny": "Y load factor, ny",
    "nz": "Z load factor, nz",
    "axb": "Body-axis x acceleration, axb, m/s^2",
    "ayb": "Body-axis y acceleration, ayb, m/s^2",
    "azb": "Body-axis z acceleration, azb, m/s^2",
    "aphir": "Rol angle acceleration, aphir, rad/s^2",
    "athetar": "Pitch angle acceleration, athetar, rad/s^2",
    "apsir": "Yaw angle acceleration, apsir, rad/s^2",
    "Ixx": "Roll moment of inertia, Ixx, kg.m^2",
    "Iyy": "Pitch moment of inertia, Iyy, kg.m^2",
    "Izz": "Yaw moment of inertia, Izz, kg.m^2",
    "Ixz": "Nose-high (low) product of inertia, Ixz, kg.m^2",
    "S": "Reference wing area, S, m^2",
    "b": "Wing span, b, m",
    "cBar": "Mean aerodynamic chord, cBar, m",
    "sfc": "Specific fuel consumption, sfc, kg/N.s",
    "Turbulence": "Turbulent conditions, Turbulence, boolean",
    "Icing": "Icing conditions, Icing, boolean",
}
